
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.12

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - name: chmod permissions
          command: chmod +x ./gradlew
      - run: ./gradlew clean build